"""Stage 1 package for Stardew Mod Manager."""

from .domain.models import (
    AppConfig,
    AppConfigValidationResult,
    GameEnvironmentStatus,
    DownloadsIntakeResult,
    DownloadsWatchPollResult,
    DuplicateUniqueIdFinding,
    InstalledMod,
    ManifestDependency,
    ManifestParseResult,
    ModUpdateReport,
    ModUpdateStatus,
    MissingDependencyFinding,
    ModManifest,
    ModsInventory,
    NexusIntegrationStatus,
    PackageFinding,
    PackageInspectionResult,
    PackageModEntry,
    PackageWarning,
    ParseWarning,
    PathValidationIssue,
    RemoteRequirementGuidance,
    RemoteModLink,
    SandboxInstallPlan,
    SandboxInstallPlanEntry,
    SandboxInstallResult,
    ScanEntryFinding,
)
from .domain.install_codes import BLOCKED, INSTALL_NEW, OVERWRITE_WITH_ARCHIVE, SandboxInstallAction
from .domain.nexus_codes import (
    NEXUS_CONFIGURED,
    NEXUS_INVALID_AUTH_FAILURE,
    NEXUS_NOT_CONFIGURED,
    NEXUS_WORKING_VALIDATED,
    NexusCredentialSource,
    NexusIntegrationState,
)
from .domain.package_codes import PackageFindingKind
from .domain.remote_requirement_codes import (
    NO_REMOTE_LINK_FOR_REQUIREMENTS,
    REQUIREMENTS_ABSENT,
    REQUIREMENTS_PRESENT,
    REQUIREMENTS_UNAVAILABLE,
    RemoteRequirementState,
)
from .domain.unique_id import canonicalize_unique_id
from .domain.scan_codes import ScanEntryKind
from .domain.update_codes import RemoteLinkProvider, UpdateState
from .domain.warning_codes import ParseWarningCode
from .services.app_state_store import (
    APP_STATE_VERSION,
    AppStateStoreError,
    load_app_config,
    save_app_config,
)

__all__ = [
    "AppConfig",
    "AppConfigValidationResult",
    "GameEnvironmentStatus",
    "DownloadsIntakeResult",
    "DownloadsWatchPollResult",
    "DuplicateUniqueIdFinding",
    "InstalledMod",
    "ManifestDependency",
    "ManifestParseResult",
    "ModUpdateReport",
    "ModUpdateStatus",
    "MissingDependencyFinding",
    "ModManifest",
    "ModsInventory",
    "NexusIntegrationStatus",
    "NexusIntegrationState",
    "NexusCredentialSource",
    "NEXUS_NOT_CONFIGURED",
    "NEXUS_CONFIGURED",
    "NEXUS_INVALID_AUTH_FAILURE",
    "NEXUS_WORKING_VALIDATED",
    "PackageFinding",
    "PackageFindingKind",
    "PackageInspectionResult",
    "PackageModEntry",
    "PackageWarning",
    "SandboxInstallAction",
    "INSTALL_NEW",
    "OVERWRITE_WITH_ARCHIVE",
    "BLOCKED",
    "ParseWarning",
    "ParseWarningCode",
    "PathValidationIssue",
    "RemoteRequirementGuidance",
    "RemoteRequirementState",
    "REQUIREMENTS_PRESENT",
    "REQUIREMENTS_ABSENT",
    "REQUIREMENTS_UNAVAILABLE",
    "NO_REMOTE_LINK_FOR_REQUIREMENTS",
    "RemoteModLink",
    "RemoteLinkProvider",
    "SandboxInstallPlan",
    "SandboxInstallPlanEntry",
    "SandboxInstallResult",
    "ScanEntryFinding",
    "ScanEntryKind",
    "UpdateState",
    "APP_STATE_VERSION",
    "AppStateStoreError",
    "canonicalize_unique_id",
    "load_app_config",
    "save_app_config",
]
