"""Stage 1 package for Stardew Mod Manager."""

from .domain.models import (
    AppConfig,
    AppConfigValidationResult,
    DownloadsIntakeResult,
    DownloadsWatchPollResult,
    DuplicateUniqueIdFinding,
    InstalledMod,
    ManifestDependency,
    ManifestParseResult,
    ModUpdateReport,
    ModUpdateStatus,
    MissingDependencyFinding,
    ModManifest,
    ModsInventory,
    PackageFinding,
    PackageInspectionResult,
    PackageModEntry,
    PackageWarning,
    ParseWarning,
    PathValidationIssue,
    RemoteModLink,
    SandboxInstallPlan,
    SandboxInstallPlanEntry,
    SandboxInstallResult,
    ScanEntryFinding,
)
from .domain.install_codes import BLOCKED, INSTALL_NEW, OVERWRITE_WITH_ARCHIVE, SandboxInstallAction
from .domain.package_codes import PackageFindingKind
from .domain.unique_id import canonicalize_unique_id
from .domain.scan_codes import ScanEntryKind
from .domain.update_codes import RemoteLinkProvider, UpdateState
from .domain.warning_codes import ParseWarningCode
from .services.app_state_store import (
    APP_STATE_VERSION,
    AppStateStoreError,
    load_app_config,
    save_app_config,
)

__all__ = [
    "AppConfig",
    "AppConfigValidationResult",
    "DownloadsIntakeResult",
    "DownloadsWatchPollResult",
    "DuplicateUniqueIdFinding",
    "InstalledMod",
    "ManifestDependency",
    "ManifestParseResult",
    "ModUpdateReport",
    "ModUpdateStatus",
    "MissingDependencyFinding",
    "ModManifest",
    "ModsInventory",
    "PackageFinding",
    "PackageFindingKind",
    "PackageInspectionResult",
    "PackageModEntry",
    "PackageWarning",
    "SandboxInstallAction",
    "INSTALL_NEW",
    "OVERWRITE_WITH_ARCHIVE",
    "BLOCKED",
    "ParseWarning",
    "ParseWarningCode",
    "PathValidationIssue",
    "RemoteModLink",
    "RemoteLinkProvider",
    "SandboxInstallPlan",
    "SandboxInstallPlanEntry",
    "SandboxInstallResult",
    "ScanEntryFinding",
    "ScanEntryKind",
    "UpdateState",
    "APP_STATE_VERSION",
    "AppStateStoreError",
    "canonicalize_unique_id",
    "load_app_config",
    "save_app_config",
]
